language: node_js

node_js:
  - "lts/*"

install:
  - npm ci

script:
  - npm run test
  - npm run prepare

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: www/stencil-qrcode-component
  github_token: $GITHUB_TOKEN
  on:
    branch: master

after_deploy:
  - npm run lh -- https://doppelganger9.github.io/stencil-qrcode-component/
