/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ErrorCorrectionLevel, OutputMode } from "./components/qr-code/enums";
export { ErrorCorrectionLevel, OutputMode } from "./components/qr-code/enums";
export namespace Components {
    interface QrCode {
        "colorDark": string;
        "colorLight": string;
        "contents": string;
        "errorCorrectionLevel": ErrorCorrectionLevel;
        "margin": number;
        "outputMode": OutputMode;
        "scale": number;
    }
}
declare global {
    interface HTMLQrCodeElement extends Components.QrCode, HTMLStencilElement {
    }
    var HTMLQrCodeElement: {
        prototype: HTMLQrCodeElement;
        new (): HTMLQrCodeElement;
    };
    interface HTMLElementTagNameMap {
        "qr-code": HTMLQrCodeElement;
    }
}
declare namespace LocalJSX {
    interface QrCode {
        "colorDark"?: string;
        "colorLight"?: string;
        "contents"?: string;
        "errorCorrectionLevel"?: ErrorCorrectionLevel;
        "margin"?: number;
        "outputMode"?: OutputMode;
        "scale"?: number;
    }
    interface IntrinsicElements {
        "qr-code": QrCode;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "qr-code": LocalJSX.QrCode & JSXBase.HTMLAttributes<HTMLQrCodeElement>;
        }
    }
}
