/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface QrCode {
    'colorDark': string;
    'colorLight': string;
    'contents': string;
    'errorCorrectionLevel': string;
    'margin': number;
    'outputMode': string;
    'scale': number;
  }
  interface QrCodeAttributes extends StencilHTMLAttributes {
    'colorDark'?: string;
    'colorLight'?: string;
    'contents'?: string;
    'errorCorrectionLevel'?: string;
    'margin'?: number;
    'outputMode'?: string;
    'scale'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'QrCode': Components.QrCode;
  }

  interface StencilIntrinsicElements {
    'qr-code': Components.QrCodeAttributes;
  }


  interface HTMLQrCodeElement extends Components.QrCode, HTMLStencilElement {}
  var HTMLQrCodeElement: {
    prototype: HTMLQrCodeElement;
    new (): HTMLQrCodeElement;
  };

  interface HTMLElementTagNameMap {
    'qr-code': HTMLQrCodeElement
  }

  interface ElementTagNameMap {
    'qr-code': HTMLQrCodeElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
