/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import { QRCodeWebComponent as QrCode } from './components/qr-code/qr-code';

interface HTMLQrCodeElement extends QrCode, HTMLElement {
}
declare var HTMLQrCodeElement: {
  prototype: HTMLQrCodeElement;
  new (): HTMLQrCodeElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "qr-code": HTMLQrCodeElement;
  }
  interface ElementTagNameMap {
      "qr-code": HTMLQrCodeElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "qr-code": JSXElements.QrCodeAttributes;
      }
  }
  namespace JSXElements {
      export interface QrCodeAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
          contents?: string,
          errorCorrectionLevel?: any,
          margin?: number,
          scale?: number,
          colorDark?: string,
          colorLight?: string,
          outputMode?: any
      }
  }
}

