name: Build, Test & Publish to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install
        run: |
          npm ci --legacy-peer-deps
 
      - name: Test and Build
        run: |
          npm run test
          npm run prepare
      
      - name: Build Storybook and move it to www dir
        run: |
          npm run build-storybook -- -o www/stencil-qrcode-component/storybook --quiet
      
      - name: Run LightHouse on static site
        run: |
          npm install -g @lhci/cli@0.9.x
          lhci autorun --staticDistDir www/stencil-qrcode-component/ --autodiscoverUrlBlocklist /storybook/
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Publish to GitHub Pages (if triggered from master)
        uses: JamesIves/github-pages-deploy-action@v4.6.9
        if: github.ref == 'refs/heads/master'
        with:
          branch: gh-pages
          folder: www/stencil-qrcode-component
