# This is a basic workflow to help you get started with Actions

name: Build, Test & Publish to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install
        run: |
          npm ci
          npm install -g @lhci/cli@0.8.x

      - name: Test and Build
        run: |
          npm run test
          npm run prepare
      
      - name: Rub LightHouse on deployed site
        run: lhci autorun

      - name: Publish to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: www/stencil-qrcode-component
